# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSRefreshExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SSRefresh/MJ', :path => '../../'
  pod 'SSRefresh/SR', :path => '../../'
  # Pods for SSRefreshExample

end
